name: flutter_news_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
 # Core Dependencies
  dartz: ^0.10.1 # Functional programming library for Dart
  get_it: ^7.7.0 # Service locator for dependency injection
  uuid: ^4.5.0 # Generates unique IDs for objects or entities
  json_annotation: 4.9.0 # Enables code generation for JSON serialization/deserialization
  equatable: ^2.0.5 # Used to prevent object reference shifts
  internet_connection_checker: ^1.0.0+1 # Checks for active internet connections
  dio: ^5.8.0+1

  # Localization
  easy_localization: ^3.0.7 # Simplifies localization and internationalization of the app
  intl: ^0.20.2 # Provides internationalization and localization facilities


  # Local Storage
  shared_preferences: ^2.3.2 # For local data storage
  hive: ^2.2.3 # A fast and lightweight NoSQL database for local data storage
  hive_flutter: ^1.1.0 # Provides simple and secure data storage with Hive in Flutter applications

  # UI Components
  font_awesome_flutter: ^10.7.0 # Provides Font Awesome icons for Flutter
  google_fonts: ^6.2.1 # Allows the use of fonts from Google Fonts

  # Image & Media
  cached_network_image: ^3.4.1 # Caches network images

  # Utilities
  infinite_scroll_pagination: ^5.1.1 # Implements infinite scrolling pagination for flutter
  collection: ^1.18.0 # Provides additional collection utilities


  # Development Tools
  device_preview: ^1.3.1 # Used for device preview

  # Animation & Effects
  shimmer: ^3.0.0 # Used for shimmer effect
  go_router: ^17.0.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0 # Code generator for JSON serialization
  build_runner: ^2.3.3 # Build system for Dart to generate code
  very_good_analysis: ^6.0.0 # Linter rules for code quality and consistency
  
flutter:

  uses-material-design: true

 