name: flutter_news_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # iOS-style system icons

  # ==================================================
  # Core
  # ==================================================
  dartz: ^0.10.1 # Functional programming helpers (Either, Option, Failure handling)
  equatable: ^2.0.5 # Value-based equality for entities and states
  get_it: ^7.7.0 # Service locator for dependency injection
  collection: ^1.18.0 # Advanced collection utilities and helpers
  json_annotation: ^4.9.0 # Annotations for JSON serialization code generation

  # ==================================================
  # App (State, Navigation, Network, Config)
  # ==================================================
  flutter_riverpod: ^2.6.1 # Reactive and scalable state management
  go_router: ^17.0.0 # Declarative and URL-based navigation
  dio: ^5.8.0+1 # Powerful HTTP client for REST APIs
  internet_connection_checker: ^1.0.0+1 # Checks device internet connectivity
  easy_localization: ^3.0.7 # Simple and scalable localization management
  intl: ^0.20.2 # Date, number, and locale-based formatting
  flutter_dotenv: ^5.2.1 # Environment variable management (.env files)

  # ==================================================
  # Storage
  # ==================================================
  shared_preferences: ^2.3.2 # Lightweight key-value local storage
  hive: ^2.2.3 # Fast local NoSQL database
  hive_flutter: ^1.1.0 # Flutter bindings for Hive
  flutter_secure_storage: ^10.0.0 # Encrypted storage for sensitive data (tokens)

  # ==================================================
  # UI & Utils
  # ==================================================
  font_awesome_flutter: ^10.7.0 # Popular icon pack for UI components
  cached_network_image: ^3.4.1 # Image loading with caching support
  shimmer: ^3.0.0 # Skeleton loading and shimmer effects
  carousel_slider: ^5.0.0 # Carousel UI component for images or content
  smooth_page_indicator: ^1.2.0+3 # Animated page indicators for carousels
  infinite_scroll_pagination: ^5.1.1 # Pagination support for infinite lists
  device_preview: ^1.3.1 # Preview app on different devices (debug only)

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0 # Code generator for JSON serialization
  build_runner: ^2.3.3 # Build system for Dart to generate code
  hive_generator: ^2.0.1 # Code generator for Hive type adapters
  very_good_analysis: ^6.0.0 # Linter rules for code quality and consistency
  mockito: ^5.4.4 # Mock library for testing
  
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/fonts/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic